name: cd
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Deploy with SSH
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }} 
            password: ${{ secrets.SSH_PASSWORD }}  
            script: | 
                cd /var/www/html/apaaja 
                git pull origin master
                yarn install
                yarn build 
                pm2 restart apaaja
